version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - vlan
    environment:
      - TZ
      - WEBPASSWORD
    volumes:
       - 'pihole/:/etc/pihole/'
       - 'dnsmasq/:/etc/dnsmasq.d/'
    # run `touch ./var-log/pihole.log` first unless you like errors
    # - './var-log/pihole.log:/var/log/pihole.log'
    dns:
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    cap_add:
      - NET_ADMIN
    restart: always

volumes:
  pihole:
  dnsmasq:

networks:
  vlan:
    driver: macvlan
    driver_opts:
      parent: ${NETWORK_INTERFACE}
    ipam:
      config:
        - subnet: ${SUBNET}
        - ip_range: ${IP_RANGE}